sudo: required
services:
  - docker

before_install:
  - docker build -t gruszatv/sslv -f ./client/Dockerfile.dev ./client

script:
  - docker run gruszatv/sslv npm test

after_success:
  - docker build -t gruszatv/sslv-client ./client
  - docker build -t gruszatv/sslv-nginx ./nginx
  - docker build -t gruszatv/sslv-server ./server
  - docker build -t gruszatv/sslv-worker ./worker
  # Log in to  docker CLI
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker
  - docker push gruszatv/sslv-client
  - docker push gruszatv/sslv-nginx
  - docker push gruszatv/sslv-server
  - docker push gruszatv/sslv-worker
